QT -= core gui
TARGET = yas-base-test
CONFIG += console
CONFIG -= app_bundle qt
TEMPLATE = app

DEFINES += \
	YAS_SERIALIZE_BOOST_TYPES=1

QMAKE_CXXFLAGS += -std=c++0x

INCLUDEPATH += \
	../../include \

LIBS += \
	-lboost_system \
	-lboost_serialization

SOURCES += main.cpp

HEADERS += \
	../../include/yas/binary_iarchive.hpp \
	../../include/yas/binary_oarchive.hpp \
	../../include/yas/json_iarchive.hpp \
	../../include/yas/json_oarchive.hpp \
	../../include/yas/text_iarchive.hpp \
	../../include/yas/text_oarchive.hpp \
	../../include/yas/config/config.hpp \
	../../include/yas/mpl/bool.hpp \
	../../include/yas/mpl/metafunctions.hpp \
	../../include/yas/mpl/type_traits.hpp \
	../../include/yas/serializers/boost_types_serializers.hpp \
	../../include/yas/serializers/qt_types_serializers.hpp \
	../../include/yas/serializers/std_types_serializers.hpp \
	../../include/yas/tools/buffer.hpp \
	../../include/yas/tools/hexdumper.hpp \
	../../include/yas/tools/noncopyable.hpp \
	../../include/yas/tools/utf8conv.hpp \
	../../include/yas/tools/version.hpp \
	../../include/yas/config/compiler/clang.hpp \
	../../include/yas/config/compiler/gcc.hpp \
	../../include/yas/config/compiler/intel.hpp \
	../../include/yas/config/compiler/msvc.hpp \
	../../include/yas/serializers/detail/has_function_serialize.hpp \
	../../include/yas/serializers/detail/has_method_serialize.hpp \
	../../include/yas/serializers/detail/information.hpp \
	../../include/yas/serializers/detail/memstream.hpp \
	../../include/yas/serializers/detail/properties.hpp \
	../../include/yas/serializers/detail/serializer_fwd.hpp \
	../../include/yas/tools/boost_preprocessor/auto_rec.hpp \
	../../include/yas/tools/boost_preprocessor/bool.hpp \
	../../include/yas/tools/boost_preprocessor/cat.hpp \
	../../include/yas/tools/boost_preprocessor/comma.hpp \
	../../include/yas/tools/boost_preprocessor/comma_if.hpp \
	../../include/yas/tools/boost_preprocessor/config.hpp \
	../../include/yas/tools/boost_preprocessor/dec.hpp \
	../../include/yas/tools/boost_preprocessor/eat.hpp \
	../../include/yas/tools/boost_preprocessor/elem.hpp \
	../../include/yas/tools/boost_preprocessor/empty.hpp \
	../../include/yas/tools/boost_preprocessor/enum_params.hpp \
	../../include/yas/tools/boost_preprocessor/error.hpp \
	../../include/yas/tools/boost_preprocessor/if.hpp \
	../../include/yas/tools/boost_preprocessor/iif.hpp \
	../../include/yas/tools/boost_preprocessor/inc.hpp \
	../../include/yas/tools/boost_preprocessor/overload.hpp \
	../../include/yas/tools/boost_preprocessor/preprocessor.hpp \
	../../include/yas/tools/boost_preprocessor/rem.hpp \
	../../include/yas/tools/boost_preprocessor/repeat.hpp \
	../../include/yas/tools/boost_preprocessor/size.hpp \
	../../include/yas/tools/boost_preprocessor/telem.hpp \
	../../include/yas/tools/boost_preprocessor/velem.hpp \
	../../include/yas/tools/boost_preprocessor/vsize.hpp \
	../../include/yas/serializers/binary/boost/boost_array_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_list_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_map_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_pair_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_set_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_tuple_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_fusion_vector_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_tuple_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_unordered_map_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/binary/boost/boost_unordered_set_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qbitarray_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qbytearray_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qchar_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qcolor_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qdate_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qdatetime_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qhash_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qlist_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qmap_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qmultihash_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qmultimap_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qpoint_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qpointf_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qpolygon_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qpolygonf_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qqueue_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qrect_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qrectf_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qregion_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qset_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qsize_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qsizef_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qstack_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qstring_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qstringlist_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qtime_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qurl_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_quuid_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvariant_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvarianthash_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvariantlist_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvariantmap_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvector2d_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvector3d_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvector4d_serializers.hpp \
	../../include/yas/serializers/binary/qt/qt_qvector_serializers.hpp \
	../../include/yas/serializers/binary/std/std_array_serializers.hpp \
	../../include/yas/serializers/binary/std/std_list_serializers.hpp \
	../../include/yas/serializers/binary/std/std_map_serializers.hpp \
	../../include/yas/serializers/binary/std/std_multimap_serializers.hpp \
	../../include/yas/serializers/binary/std/std_multiset_serializers.hpp \
	../../include/yas/serializers/binary/std/std_pair_serializers.hpp \
	../../include/yas/serializers/binary/std/std_set_serializers.hpp \
	../../include/yas/serializers/binary/std/std_string_serializers.hpp \
	../../include/yas/serializers/binary/std/std_tuple_serializers.hpp \
	../../include/yas/serializers/binary/std/std_unordered_map_serializers.hpp \
	../../include/yas/serializers/binary/std/std_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/binary/std/std_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/binary/std/std_unordered_set_serializers.hpp \
	../../include/yas/serializers/binary/std/std_vector_serializers.hpp \
	../../include/yas/serializers/binary/std/std_wstring_serializers.hpp \
	../../include/yas/serializers/binary/utility/autoarray_serializers.hpp \
	../../include/yas/serializers/binary/utility/buffer_serializers.hpp \
	../../include/yas/serializers/binary/utility/pod_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_array_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_list_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_map_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_pair_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_set_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_tuple_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_fusion_vector_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_tuple_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_unordered_map_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/json/boost/boost_unordered_set_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qbitarray_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qbytearray_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qchar_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qcolor_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qdate_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qdatetime_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qhash_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qlist_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qmap_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qmultihash_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qmultimap_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qpoint_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qpointf_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qpolygon_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qpolygonf_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qqueue_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qrect_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qrectf_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qregion_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qset_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qsize_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qsizef_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qstack_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qstring_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qstringlist_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qtime_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qurl_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_quuid_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvariant_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvarianthash_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvariantlist_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvariantmap_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvector2d_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvector3d_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvector4d_serializers.hpp \
	../../include/yas/serializers/json/qt/qt_qvector_serializers.hpp \
	../../include/yas/serializers/json/std/std_array_serializers.hpp \
	../../include/yas/serializers/json/std/std_list_serializers.hpp \
	../../include/yas/serializers/json/std/std_map_serializers.hpp \
	../../include/yas/serializers/json/std/std_multimap_serializers.hpp \
	../../include/yas/serializers/json/std/std_multiset_serializers.hpp \
	../../include/yas/serializers/json/std/std_pair_serializers.hpp \
	../../include/yas/serializers/json/std/std_set_serializers.hpp \
	../../include/yas/serializers/json/std/std_string_serializers.hpp \
	../../include/yas/serializers/json/std/std_tuple_serializers.hpp \
	../../include/yas/serializers/json/std/std_unordered_map_serializers.hpp \
	../../include/yas/serializers/json/std/std_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/json/std/std_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/json/std/std_unordered_set_serializers.hpp \
	../../include/yas/serializers/json/std/std_vector_serializers.hpp \
	../../include/yas/serializers/json/std/std_wstring_serializers.hpp \
	../../include/yas/serializers/json/utility/buffer_serializer.hpp \
	../../include/yas/serializers/text/boost/boost_array_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_list_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_map_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_pair_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_set_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_tuple_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_fusion_vector_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_tuple_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_unordered_map_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/text/boost/boost_unordered_set_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qbitarray_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qbytearray_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qchar_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qcolor_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qdate_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qdatetime_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qhash_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qlist_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qmap_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qmultihash_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qmultimap_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qpoint_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qpointf_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qpolygon_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qpolygonf_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qqueue_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qrect_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qrectf_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qregion_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qset_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qsize_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qsizef_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qstack_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qstring_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qstringlist_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qtime_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qurl_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_quuid_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvariant_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvarianthash_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvariantlist_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvariantmap_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvector2d_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvector3d_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvector4d_serializers.hpp \
	../../include/yas/serializers/text/qt/qt_qvector_serializers.hpp \
	../../include/yas/serializers/text/std/std_array_serializers.hpp \
	../../include/yas/serializers/text/std/std_list_serializers.hpp \
	../../include/yas/serializers/text/std/std_map_serializers.hpp \
	../../include/yas/serializers/text/std/std_multimap_serializers.hpp \
	../../include/yas/serializers/text/std/std_multiset_serializers.hpp \
	../../include/yas/serializers/text/std/std_pair_serializers.hpp \
	../../include/yas/serializers/text/std/std_set_serializers.hpp \
	../../include/yas/serializers/text/std/std_string_serializers.hpp \
	../../include/yas/serializers/text/std/std_tuple_serializers.hpp \
	../../include/yas/serializers/text/std/std_unordered_map_serializers.hpp \
	../../include/yas/serializers/text/std/std_unordered_multimap_serializers.hpp \
	../../include/yas/serializers/text/std/std_unordered_multiset_serializers.hpp \
	../../include/yas/serializers/text/std/std_unordered_set_serializers.hpp \
	../../include/yas/serializers/text/std/std_vector_serializers.hpp \
	../../include/yas/serializers/text/std/std_wstring_serializers.hpp \
	../../include/yas/serializers/binary/utility/usertype_serializers.hpp \
	 ../../include/yas/serializers/text/utility/usertype_serializers.hpp \
	 ../../include/yas/serializers/text/utility/pod_serializers.hpp \
	 ../../include/yas/serializers/text/utility/autoarray_serializers.hpp \
	 ../../include/yas/serializers/text/utility/buffer_serializers.hpp \
	 ../../include/yas/serializers/binary/std/std_forward_list_serializers.hpp \
	 ../../include/yas/serializers/binary/std/std_bitset_serializers.hpp \
	 ../../include/yas/serializers/json/std/std_forward_list_serializers.hpp \
	 ../../include/yas/serializers/json/std/std_bitset_serializers.hpp \
	 ../../include/yas/serializers/text/std/std_forward_list_serializers.hpp \
	 ../../include/yas/serializers/text/std/std_bitset_serializers.hpp
