
// Copyright (c) 2010-2012 niXman (i dot nixman dog gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef _yas_test__tuple_hpp__included_
#define _yas_test__tuple_hpp__included_

#include <yas/detail/tools/hexdumper.hpp>

#if defined(YAS_HAS_BOOST_TUPLE)
//#include <boost/tuple/tuple_comparison.hpp>
#endif // defined(YAS_HAS_BOOST_TUPLE)

template<typename OA, typename IA>
bool tuple_test() {
#if defined(YAS_HAS_BOOST_TUPLE)
	boost::tuples::tuple<int, int> t1(1, 3), t2;

	OA oa;
	oa & t1;

	IA ia(oa.get_intrusive_buffer());
	ia & t2;

	if ( t1 != t2 ) {
		std::cout << "TUPLE test failed!" << std::endl;
		return false;
	}
#endif // defined(YAS_HAS_BOOST_TUPLE)

#if defined(YAS_HAS_STD_TUPLE)
	std::tuple<int, int> t3(4, 7), t4;
	OA oa2;
	oa2 & t3;

	IA ia2(oa2.get_intrusive_buffer());
	ia2 & t4;

	if ( t3 != t4 ) {
		std::cout << "TUPLE test failed!" << std::endl;
		return false;
	}
#endif // defined(YAS_HAS_STD_TUPLE)
	return true;
}

#endif // _yas_test__tuple_hpp__included_
