
// Copyright (c) 2010-2012 niXman (i dot nixman dog gmail dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef _yas_test__unordered_map_hpp__included_
#define _yas_test__unordered_map_hpp__included_

#if defined(YAS_HAS_STD_UNORDERED) || defined(YAS_HAS_BOOST_UNORDERED)

template<typename OA, typename IA>
bool unordered_map_test() {
#if defined(YAS_HAS_STD_UNORDERED)
	OA oa;
	std::unordered_map<int, int> pod_map, pod_map2;
	pod_map[1] = 2;
	pod_map[2] = 3;
	pod_map[3] = 4;

	oa & pod_map;

	IA ia(oa.get_intrusive_buffer());
	ia & pod_map2;

	if ( pod_map != pod_map2 ) {
		std::cout << "UNORDERED_MAP deserialization error! [1]" << std::endl;
		return false;
	}

	std::unordered_map<int, std::string> map, map2;
	map[1] = "1";
	map[2] = "2";
	map[3] = "3";

	OA oa2;
	oa2 & map;

	IA ia2(oa2.get_intrusive_buffer());
	ia2 & map2;

	if ( map != map2 ) {
		std::cout << "UNORDERED_MAP deserialization error! [2]" << std::endl;
		return false;
	}

	std::unordered_map<std::string, int> map3, map4;
	map3["1"] = 1;
	map3["2"] = 2;
	map3["3"] = 3;

	OA oa3;
	oa3 & map3;

	IA ia3(oa3.get_intrusive_buffer());
	ia3 & map4;

	if ( map3 != map4 ) {
		std::cout << "UNORDERED_MAP deserialization error! [3]" << std::endl;
		return false;
	}
#endif // defined(YAS_HAS_STD_UNORDERED)

#if defined(YAS_HAS_BOOST_UNORDERED)
	boost::unordered_map<int, int> map5, map6;
	map5.insert(std::make_pair(1, 2));
	map5.insert(std::make_pair(2, 3));
	map5.insert(std::make_pair(3, 4));
	map5.insert(std::make_pair(4, 5));

	OA oa4;
	oa4 & map5;

	IA ia4(oa4.get_intrusive_buffer());
	ia4 & map6;

	if ( map5 != map6 ) {
		std::cout << "UNORDERED_MAP deserialization error! [4]" << std::endl;
		return false;
	}
#endif // defined(YAS_HAS_BOOST_UNORDERED)
	return true;
}

#endif // #if defined(YAS_HAS_STD_UNORDERED) || defined(YAS_HAS_BOOST_UNORDERED)

#endif // _yas_test__unordered_map_hpp__included_
