
// Copyright (c) 2010-2014 niXman (i dot nixman dog gmail dot com). All
// rights reserved.
//
// This file is part of YAS(https://github.com/niXman/yas) project.
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef _yas__qt_types_serializers_hpp
#define _yas__qt_types_serializers_hpp

#include <yas/detail/config/config.hpp>

#if defined(YAS_SERIALIZE_QT_TYPES)

#include <yas/serializers/binary/qt/qt_qbitarray_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qbitarray_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qbitarray_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qbytearray_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qbytearray_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qbytearray_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qchar_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qchar_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qchar_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qcolor_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qcolor_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qcolor_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qdate_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qdate_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qdate_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qdatetime_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qdatetime_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qdatetime_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qhash_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qhash_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qhash_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qlist_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qlist_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qlist_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qmap_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qmap_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qmap_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qmultihash_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qmultihash_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qmultihash_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qmultimap_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qmultimap_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qmultimap_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qpoint_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qpoint_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qpoint_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qpointf_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qpointf_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qpointf_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qpolygon_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qpolygon_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qpolygon_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qpolygonf_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qpolygonf_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qpolygonf_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qqueue_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qqueue_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qqueue_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qrect_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qrect_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qrect_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qrectf_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qrectf_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qrectf_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qregion_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qregion_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qregion_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qset_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qset_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qset_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qsize_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qsize_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qsize_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qsizef_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qsizef_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qsizef_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qstack_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qstack_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qstack_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qstring_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qstring_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qstring_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qstringlist_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qstringlist_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qstringlist_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qtime_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qtime_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qtime_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qurl_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qurl_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qurl_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_quuid_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_quuid_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_quuid_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvariant_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvariant_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvariant_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvarianthash_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvarianthash_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvarianthash_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvariantlist_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvariantlist_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvariantlist_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvariantmap_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvariantmap_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvariantmap_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvector2d_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvector2d_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvector2d_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvector3d_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvector3d_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvector3d_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvector4d_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvector4d_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvector4d_serializers.hpp.hpp>

#include <yas/serializers/binary/qt/qt_qvector_serializers.hpp.hpp>
#include <yas/serializers/text/qt/qt_qvector_serializers.hpp.hpp>
#include <yas/serializers/json/qt/qt_qvector_serializers.hpp.hpp>

#endif // defined(YAS_SERIALIZE_QT_TYPES)

#endif // _yas__qt_types_serializers_hpp
