
// Copyright (c) 2010-2016 niXman (i dot nixman dog gmail dot com). All
// rights reserved.
//
// This file is part of YAS(https://github.com/niXman/yas) project.
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef _yas__detail__version_hpp
#define _yas__detail__version_hpp

#include <yas/detail/type_traits/properties.hpp>

// YAS_VERSION % 100 is the patch level
// YAS_VERSION / 100 % 1000 is the minor version
// YAS_VERSION / 100000 is the major version

#define YAS_VERSION() 400000
#define YAS_VERSION_STRING() "1.0.0"

namespace yas {
namespace detail {

enum yas_version {
	 binary_archive_version = 3
	,text_archive_version = 1
	,json_archive_version = 0
};

template<yas::archive_type::type>
struct archive_version_by_type;

template<>
struct archive_version_by_type<archive_type::binary> {
	enum { version = binary_archive_version };
};
template<>
struct archive_version_by_type<archive_type::text> {
	enum { version = text_archive_version };
};
template<>
struct archive_version_by_type<archive_type::json> {
	enum { version = json_archive_version };
};

} // namespace detail
} // namespace yas

#endif // _yas__detail__version_hpp
